- hosts: all
  tasks:
    - name: Install Python and pip
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - python3
          - python3-pip

    - name: Copy project files
      copy:
        src: /local/path/to/task_manager/
        dest: /home/ubuntu/task_manager/
