apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-manager
  template:
    metadata:
      labels:
        app: task-manager
    spec:
      containers:
      - name: task-manager
        image: mytaskmanager:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_USER
          value: "admin"
        - name: DB_PASSWORD
          value: "admin123"
        securityContext:
          runAsUser: 0
          privileged: true
      restartPolicy: Always
